# Generated by Django 5.0.2 on 2024-03-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.CharField(default='zkzk', max_length=20),
            preserve_default=False,
        ),
    ]
