# Generated by Django 5.0.2 on 2024-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_drugcategory_drugs_data_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/drug/category/'),
        ),
    ]
