# Generated by Django 5.0.2 on 2024-03-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('sender_message', models.TextField()),
                ('bot_message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
